config/routes.rb
Kutang::Application.routes.draw do

  devise_for :users

  controller :pages do
    get "privacy_policy"
    get "program_policy"
    get "terms_of_use"
    get "about"
    get "user_safety"
    get "help"
    get 'thanks'
    get 'show'
  end

  controller :users do
    get "mykutangaza"
    get "pending_ads"
    get "onhold_ads"
    get "expired_ads"

    get "promote_my_ads"
    get "my_order"
    get "search_my_ads"
    get "search_user"
  end

  resources :categories

  root :to => 'welcome#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  CATEGORY = ["Buy and Sell", "Services", "Cars and Vehicles", "Pets", "Community", "Real Estate", "Jobs", "Resumes"]
  has_many :subcategories
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(params[:category])

    if @category.save
      redirect_to admin_categories_url, notice: 'Category was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(params[:category])
      redirect_to admin_categories_url, notice: 'Category was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to admin_categories_url
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
		@categories = Category.all
	end
	
	def show
		@subcategory = Subcategory.where(:name => params[:name])
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_all_categories.html.erb
<div class="row-fuid">
  <div class="span12">
    <%count =0%>
  	<%@categories.each do |category|%>
      <%count += 1%>
      <div class="span3 <%= 'margin-top210' if count==7  %> <%= 'margin-top195' if count==5  %> <%= 'margin-top240' if count==8  %> " >
    	  <p><%=category.name%></p>
    	  <%category.subcategories.each do |sub_cat| %>
  	  	  <%= link_to sub_cat.name, category_path(sub_cat.name)%><br>
  	  	  <%end%>
  	  </div>	
  	<%end%>
  </div>
</div>

app/views/categories/index.html.erb
<!--left side-->
<div class="left">
  <!--slider-->
  <div class="gallery">
    <div class="inner">
      <span style="font-size: 15px;font-weight: bold; padding: 20px" > Select a Category. </span>
    </div>
  </div>
  <!--slider end-->
  <div>
    <%= render partial: 'all_categories'%>
  </div>
  <!--services-->
</div>

app/views/categories/show.html.erb
<div class="container">
  <div class="row-fluid">
    <div class="span2">
      <strong> </strong>
    </div>
  </div>
</div>